/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;

import java.sql.Connection;
import static pertemuan10.dbkoneksi.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tangkas
 * 24 Mei 2025
 */
public class FormTeman extends javax.swing.JFrame {
    String edNama;
    DefaultTableModel TM = new DefaultTableModel();

    /**
     * Creates new form FormTeman
     */
    public FormTeman() throws SQLException {
        initComponents();
        
        TTM.setModel(TM);
        TM.addColumn("No");
        TM.addColumn("namateman");
        TM.addColumn("alamat");
        TM.addColumn("telp");

        this.dtTemanList();
        fielddisEnabled(false);
        tombolisEnabled(false);
        btnTambah.setEnabled(true);
        btnClose.setEnabled(true);
        

    }
    
    private void fielddisEnabled(boolean opsi){
        txNAMA.setEditable(opsi);
        txALAMAT.setEditable(opsi);
        txTELP.setEditable(opsi);
        
    }
    private void tombolisEnabled(boolean opsi){
        btnTambah.setEnabled(opsi);
        btnUbah.setEnabled(opsi);
        btnHapus.setEnabled(opsi);
        btnClose.setEnabled(opsi);
  
    }
    private void resetForm(){
        txNAMA.setText("");
        txALAMAT.setText("");
        txTELP.setText("");
        
    }
    /*CURD*/
    private void storeData() throws SQLException{
        
        String namateman = txNAMA.getText();
        String alamat = txALAMAT.getText();
        String telp = txTELP.getText();
        
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("INSERT INTO datateman(namateman, alamat, telp) VALUES(?,?,?) ;");
        PS.setString(1, namateman);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.executeUpdate();
        
        ResultSet RS = PS.executeQuery();
    }
    private void updateData()throws SQLException{
        String namateman = txNAMA.getText();
        String alamat = txALAMAT.getText();
        String telp = txTELP.getText();
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("UPDATE datateman SET namateman=?, alamat=?, telp=? WHERE namateman=?;");
        PS.setString(1, namateman);
        PS.setString(2, alamat);
        PS.setString(3, telp);
        PS.setString(4, this.edNama);
        PS.executeUpdate();
        
        ResultSet RS = PS.executeQuery();

    }
    private void destroyData() throws SQLException{
        String namateman = txNAMA.getText();
        String alamat = txALAMAT.getText();
        String telp = txTELP.getText();
        
        
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("DELETE datateman WHERE namateman;");
        PS.setString(1, namateman);
        PS.executeUpdate();
        
        ResultSet RS = PS.executeQuery();
    }
    /*CURD*/
    private void dtTemanList() throws SQLException{
        
                
        Connection cnn = koneksi();
        PreparedStatement PS = cnn.prepareStatement("SELECT * FROM datateman;");
        ResultSet RS = PS.executeQuery();
        
        
        TM.getDataVector().removeAllElements();
        TM.fireTableDataChanged();
        
        while(RS.next()){
            Object[]dta = new Object[4];
                dta[0] = RS.getInt("idteman");
                dta[1] = RS.getString("namateman");
                dta[2] = RS.getString("alamat");
                dta[3] = RS.getString("telp");
                
                
                
                
            TM.addRow(dta);
            
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txNAMA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txALAMAT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txTELP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTM = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Teman");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(250, 250));
        setResizable(false);

        txNAMA.setName("txNAMA"); // NOI18N
        txNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNAMAActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Alamat");

        txALAMAT.setName("txALAMAT"); // NOI18N

        jLabel3.setText("Telp");

        txTELP.setName("txTELP"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setText("Data Teman");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        TTM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nama", "", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TTM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TTM);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNAMA)
                            .addComponent(txALAMAT)
                            .addComponent(txTELP, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(78, 78, 78)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose))
                            .addComponent(btnUbah))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTELP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnHapus)
                            .addComponent(btnClose))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNAMAActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    if (btnTambah.getText().equals("Tambah")) {
    tombolisEnabled(false);
    btnTambah.setText("Simpan");
    btnClose.setText("Batal");
    btnTambah.setEnabled(true);
    btnClose.setEnabled(true);
    resetForm();    
    } else {
    btnTambah.setText("Tambah");
    btnClose.setText("Close");
    try{
        storeData();
        dtTemanList();
    }catch (SQLException ex) {
        Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void TTMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTMMouseClicked
//        String sql = "SELECT * FROM datateman WHERE idteman="+TTM.getValueAt( TTM.getSelectedRow(), 0 )+";";
//        Connection cnn = koneksi();
//        PreparedStatement PS = null;
//        try {
//            PS = cnn.prepareStatement(sql);
//        } catch (SQLException ex) {
//            Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        try {
//            ResultSet RS = PS.executeQuery();
//            txNAMA.setText(RS.getString("namateman"));
//            txALAMAT.setText(RS.getString("alamat"));
//            txTELP.setText(RS.getString("telp"));
//            
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
//        }
        txNAMA.setText(TTM.getValueAt( TTM.getSelectedRow(), 1 ).toString());
        txALAMAT.setText(TTM.getValueAt(TTM.getSelectedRow(), 2 ).toString());
        txTELP.setText(TTM.getValueAt(TTM.getSelectedRow(), 3 ).toString());
        
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
       
    }//GEN-LAST:event_TTMMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String isNama = txNAMA.getText();
        int jopsi = JOptionPane.showOptionDialog(this,
                "Apakah yakin ingin menghapus data "+isNama+"?", 
                "Konfirmasi Hapus Data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, 
                null, null, null);
        if(jopsi == JOptionPane.YES_OPTION){
            try {
                destroyData();
                dtTemanList();
                
                resetForm();
                btnUbah.setEnabled(false);
                btnHapus.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if(btnUbah.getText().equals("Ubah")){
            btnUbah.setText("Simpan");
            btnClose.setText("Batal");
            tombolisEnabled(false);
            btnUbah.setEnabled(true);
            btnClose.setEnabled(true);
            btnClose.setEnabled(true);
            fielddisEnabled(true);
            this.edNama = txNAMA.getText();
        }else{
            try {
                updateData();
                dtTemanList();
            } catch (SQLException ex) {
                Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnUbah.setText("Ubah");
            btnClose.setText("Tutup");
            btnTambah.setEnabled(true);
            btnHapus.setEnabled(true);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int jopsi = JOptionPane.showOptionDialog(this, "yakin akan menutup aplikasi?", "konfirmasi tutup aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (jopsi == JOptionPane.YES_OPTION){
        System.exit(0);
        }
        else{
            resetForm();
            fielddisEnabled(false);
            btnTambah.setText("Tambah");
            btnClose.setText("Tutup");
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormTeman().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormTeman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TTM;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txALAMAT;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txTELP;
    // End of variables declaration//GEN-END:variables

    
}
